services:
     - type: web
       name: slack-bot
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: square_test.py
       envVars:
         - key: SLACK_BOT_TOKEN
           sync: false
         - key: PORT
           value: 10000
   