services:
  - type: web
    name: slack-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn square_test:flask_app
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000
    disk:
      name: pip-cache
      mountPath: /root/.cache/pip